--- #YAML:1.0
name:               Wx-Perl-DataWalker
version:            0.02
abstract:           Perl extension for blah blah blah
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::XSAccessor:  0.06
    Devel::Size:        0.71
    Scalar::Util:       0
    Wx:                 0.88
    YAML::XS:           0.32
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
